### ISSUE TITLE
Missing pages from the sidebar

### ISSUE THREAD

**Issue by debone** [statamic/v2-docs#105]
These two pages are missing from the sidebar

https://docs.statamic.com/tags
https://docs.statamic.com/addons/getting-started

**Comment by jackmcdade** [comment]
Tags are right there: 
![image](https://cloud.githubusercontent.com/assets/44739/18998183/81c7d1b6-8705-11e6-88d4-e943efd77f2b.png)

**Comment by debone** [comment]
I mean when you enter this page, you are on the `/tags` page and the sidebar doesn't have it, and it has a nice summary of what each tag does. Once in some sub like `/tags/relate`, you need to return to the main docs or delete the `/relate` part from the url

**Comment by jackmcdade** [comment]
Screenshot?

**Comment by debone** [comment]
![image](https://cloud.githubusercontent.com/assets/763457/19014196/9ca35686-87e6-11e6-9689-db8ce554cbb4.png)
