### ISSUE TITLE
On the topic of securing Statamic installation

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-docs#11]
**Some notes on my experience with moving Statamic installation above webroot**
- `.env` should be left in the `public` folder, otherwise it won't be recognized by the app
- In the docs, it says that `If you have moved the please file, you will need to adjust it in the same fashion.`. If you move `please` above root, you don't need to change anything since `please` and `statamic` are on the same level
- I actually leave my `themes` folder above root, inside the `site` folder and set up `gulp` to output the minified `js` and `css` to `public/assets/themes/js` and `public/assets/themes/css`

**Comment by jasonvarga** [comment]
The `.env` needing to be in the `public` folder was a mistake that was fixed (can't remember what version). It can now be left in your root.
