### ISSUE TITLE
Missing docs for factories on the /addons/data-factories page

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-docs#116]
The links to the specific factories at the bottom of this page throw a 404.

https://docs.statamic.com/addons/data-factories

**Comment by thestepafter** [comment]
Here are additional details:

404: https://docs.statamic.com/addons/classes/entryfactory
From: EntryFactory  https://docs.statamic.com/addons/data-factories

404: https://docs.statamic.com/addons/classes/globalfactory
From: GlobalFactory https://docs.statamic.com/addons/data-factories

404: https://docs.statamic.com/addons/classes/contentfactory
From: ContentFactory    https://docs.statamic.com/addons/data-factories

404: https://docs.statamic.com/addons/classes/listeners
From: Listener  https://docs.statamic.com/addons/control-panel

404: https://docs.statamic.com/addons/filters
From: custom filter https://docs.statamic.com/tags/taxonomy
From: Read more about custom filters    https://docs.statamic.com/tags/taxonomy

404: https://docs.statamic.com/addons/classes/api/folder
From: folders   https://docs.statamic.com/knowledge-base/filesystems

404: https://docs.statamic.com/addons/classes/pagefactory
From: PageFactory   https://docs.statamic.com/addons/data-factories

404: https://docs.statamic.com/addons/classes/api/file
From: files https://docs.statamic.com/knowledge-base/filesystems

404: https://docs.statamic.com/addons/classes/termfactory
From: TermFactory   https://docs.statamic.com/addons/data-factories

404: https://docs.statamic.com/docs/tags/search
From: Search Tag    https://docs.statamic.com/search

404: https://docs.statamic.com/addons/classes/navigation
From: add your own items to the navigation  https://docs.statamic.com/addons/events

**Comment by jasonvarga** [comment]
Thanks for reporting these. They're all fixed now.
