### ISSUE TITLE
Add a link to creating widgets on the CP page

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-docs#139]
On this page:
https://docs.statamic.com/control-panel

State which widgets work out of the box, and link to this page as a guide on how to make more:
https://docs.statamic.com/addons/classes/widget

**Comment by jackmcdade** [comment]
We now have a Widgets section: http://docs.statamic.com/widgets

**Comment by dannyuk1982** [comment]
Is that the right URL? ( docs.dev )

**Comment by jackmcdade** [comment]
You know it's not.

**Comment by dannyuk1982** [comment]
I did, but I didn't know what it was meant to be!
