### ISSUE TITLE
Assets Add-ons API is outdated

### ISSUE THREAD

**Issue by debone** [statamic/v2-docs#145]
I'm creating an issue because I'm not sure which of these APIs are updated or not:

Statamic\API\Asset
Statamic\API\Assets
Statamic\Assets\Asset

The first one is not featured on the docs and the second one has no notice about deprecation.

**Comment by jasonvarga** [comment]
`Statamic\API\Assets` is deprecated.
See: https://docs.statamic.com/addons/api/deprecations/v2.1
This URL was incorrect / showing the wrong thing until a moment ago, I just adjusted it.

`Statamic\API\Asset` is here: https://docs.statamic.com/addons/api/api-asset
This is what you'd normally use as an entry point into dealing with assets.

`Statamic\Assets\Asset` is what is usually returned by the API class. This is "an asset".
It's over here: https://docs.statamic.com/addons/api/asset

**Comment by debone** [comment]
Thanks, it was my mistake.
