### ISSUE TITLE
Laravel Packages

### ISSUE THREAD

**Issue by bognarl** [statamic/v2-docs#149]
Hi guys!

I was wondering if it is possible to use Laravel Packages from https://packagist.org, and if so, how?
I tried to add composer.json to my addon folder, then php please addon:refresh, the required vendor has been added but It seems I can't reference my vendor.

The package I tried was this: https://packagist.org/packages/mitni/laravel-google-spreadsheet

I inserted the `use Mitni\Google\GoogleSpreadsheet;` line in my addon's controller then as Mitni wrote `$client = GoogleSpreadsheet::getClient("the/path/to/credential.json");`, however I always get an error saying:
`Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Mitni\Spreadsheet\GoogleSpreadsheet' not found in ...`

What could be the problem? Can somebody help me?

Thanks in advance

**Comment by jackmcdade** [comment]
This would be a better question for [the Lodge](https://lodge.statamic.com) or [Slack](https://slack.statamic.com) :)
