### ISSUE TITLE
https://docs.statamic.com/modifiers/starts_with

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-docs#151]
https://docs.statamic.com/modifiers/starts_with

Says a pipe is needed when using the syntax starts_with="something"

This doesn't work, not sure if a bug, or doc error

**Comment by jackmcdade** [comment]
There are two formats:

```
{{ var starts_with="something" }}
{{ var | starts_with:something }}
```

**Comment by dannyuk1982** [comment]
Yup, you ain't fooling anyone @jackmcdade !

<img width="425" alt="screen shot 2016-12-08 at 16 52 49" src="https://cloud.githubusercontent.com/assets/7669885/21018951/cb9d2010-bd66-11e6-967c-37fd42d90a16.png">

Thanks for the quick fix

**Comment by jackmcdade** [comment]
Ahh, that was @jasonvarga. I'm late to the party. Thanks Danny!
