### ISSUE TITLE
Addon controller authentication/security is not documented

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-docs#152]
By default all addon routes are accessible without authentication, this should be documented with a warning.

If only super users should be able to access the method `$this->authorize('super')` must be called at the top of the method.

```
    public function index()
    {
        $this->authorize('super');

        return $this->view('index');
    }
```

Maybe it would be a good idea to add this call to the skeleton code.

**Comment by jasonvarga** [comment]
Since 2.8, this is done automatically.
