### ISSUE TITLE
Add-on Naming Convention

### ISSUE THREAD

**Issue by DavidStrada** [statamic/v2-docs#154]
Would you accept a PR, to add in your docs a naming convention clause.

Ran into this situation ( bugs) when I was creating an add-on.

add-on name `SiteBuilder` should have been `Sitebuilde` resulting on 1+ hour of debugging.

**Comment by jackmcdade** [comment]
It is in there in fact: <http://docs.statamic.com/addons/getting-started#code-structure>

**Comment by DavidStrada** [comment]
DavidStrada commented on `Jan 3 ` 😒

**Comment by jackmcdade** [comment]
?
