### ISSUE TITLE
Configure > Settings, not System > Settings

### ISSUE THREAD

**Issue by aqeelfikree** [statamic/v2-docs#155]
First paragraph in here: [https://docs.statamic.com/settings](https://docs.statamic.com/settings)

`Configure > Settings`, not `System > Settings`

**Comment by edalzell** [comment]
You can do a PR @aqeelfikree? There's an Edit button at the top of the pages.

**Comment by aqeelfikree** [comment]
True. I was just being a bit lazy.

**Comment by aqeelfikree** [comment]
Update: PR done.
