### ISSUE TITLE
Mislabeled code snippet?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#157]
On page https://docs.statamic.com/theming, under the heading, "Rendering That Template", the code snippet when displayed on the web page shows a right-hand label of "TEMPLATE." However, I believe it is in fact a "LAYOUT" snippet that's being displayed.

FYI, I clicked the [EDIT] button to make this suggested change, but despite looking around line 116 and thereabouts on https://github.com/statamic/docs/edit/master/content/collections/docs/theming.md I couldn't figure out where the label was being applied. Hence this request being made as an "issue."

(NB. I did make an edit suggestion to the paragraph between the subhead and the code snippet.)

**Comment by jackmcdade** [comment]
A layout is a type of template, actually. Thanks for taking the time and consideration!l tho!

**Comment by iDGS** [comment]
O. OK. So, by extension, would this be an accurate Venn Diagram?


![templates-sqz](https://cloud.githubusercontent.com/assets/1248937/21724426/473d5a62-d402-11e6-8a92-81134d621b18.jpeg)

I.e., "All LAYOUTS and PARTIALS are TEMPLATES, but there are TEMPLATES that are neither LAYOUTS nor PARTIALS, and a PARTIAL is not a LAYOUT, nor is a LAYOUT a PARTIAL."

(Jus' tryin' to understand stuff better—TIA ;-)

**Comment by jackmcdade** [comment]
If you wanna be really really specific, yes that's accurate. The way i see it though, is that any of the files with HTML in them are "templates" (lowercase "t"). Layouts and partials are just templates with a special purpose.

**Comment by iDGS** [comment]
Works for me. As you may have noticed, I have a knack for stumbling over vocabulary, so this explanation helps a lot! 👍
