### ISSUE TITLE
description missing: modifier `in_array`

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#158]
YMMV, but all I see is an empty box

**Comment by iDGS** [comment]
Also here: https://docs.statamic.com/modifiers/merge

**Comment by jackmcdade** [comment]
Yes this is a known flexbox issue we need to fix. Thanks! No need to list all the places it affects :)

**Comment by jackmcdade** [comment]
Sorry, commented on the wrong thread. Meant to be on #160

**Comment by iDGS** [comment]
OK. Then, here's another: https://docs.statamic.com/modifiers/modify_date

:-)

**Comment by iDGS** [comment]
(I'm noting these while actually chasing something else... stay tuned... :-)

**Comment by jackmcdade** [comment]
3 issues in one, fancy!

**Comment by iDGS** [comment]
(Dog was playing w/ my iPad—sorry)

**Comment by jackmcdade** [comment]
Duplicate of #18
