### ISSUE TITLE
Layout bug: Min width of descriptions depends on intro text?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#160]
On a wide screen, have a look at https://docs.statamic.com/modifiers/is_weekday. At least on my laptop, there's lots of whitespace left and right of the main content block, but the "TEMPLATE" label in the example partially covers the demonstrated use of the modifier itself.

It seems the description block's width is being determined by the width of the intro paragraph's text. See also https://docs.statamic.com/modifiers/is_weekend and https://docs.statamic.com/modifiers/is_yesterday for comparison.

No problem if there's a line wrap. Compare: https://docs.statamic.com/modifiers/collapse_whitespace

**Comment by iDGS** [comment]
Minimal case: https://docs.statamic.com/modifiers/merge (which is empty)

**Comment by jackmcdade** [comment]
Yes this is a known flexbox issue we need to fix. Thanks! No need to list all the places it affects :)
