### ISSUE TITLE
Piping hot?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#162]
OK. Quick story: I glanced at the default layout for Redwood, and I saw:
```
    <title>{{ title ensure_right=" / " }}{{ site_name }}</title>
```

which made me think, Eh? That's odd, I thought all modifiers had to have a pipe separator (`|`) in front of them, as in
```
{{ string | lower }}
```

So, I went looking in the docs, and sure enough, *most* of them do.

However, there are a few exceptions. These below are shown without a leading pipe in the docs:
```
  count_substring
  divide
  ensure_left
  ensure_right
  format
  format_localized
  format_number
  group_by
  insert
  regex_replace
  replace
```

(Note: 
```
  remove_left
  remove_right
```

*do* show a pipe prefix so there's a little psychological broken symmetry kind of thing there.)

Meanwhile these, I dunno, because I couldn't see the descriptions:
```
  in_array
  merge
  modify_date
```

And
```
 sort
```

was a kind of special case, because it's shown in examples both with and without a pipe.

I haven't had the chance to go test them all—\*sigh\*—so I don't actually know the truth of the matter, but as written it seems at least potentially confusing.

That initial example of
```
    <title>{{ title ensure_right=" / " }}{{ site_name }}</title>
```

certainly seems to work just fine, so I'm all ¯\_(ツ)_/¯ per usual.

Bigger picture: I *very*happy you gents are out there on the front lines slaying actual Dragons, capital "D," rather than chasing teensy bunnies, small "b," like these! Nevertheless, I thought I'd at least log them here, in the event that some day there's something that (eventually) might want some attention.

Plus, during this zoom-through the docs, I happened to find a few other teeny typos and such that I reported elsewhere, so it was moderately worthwhile. :-)

**Comment by jackmcdade** [comment]
The two syntaxes are documented very clearly in the docs:  https://docs.statamic.com/antlers#variable-modifiers
