### ISSUE TITLE
https://docs.statamic.com/tags/collection#pagination missing limit on posts tag

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-docs#203]
In this section: https://docs.statamic.com/tags/collection#pagination

It looks like the `{{ posts }}` also has to have `limit="10"` on, for the limit to be respected.

**Comment by jackmcdade** [comment]
That's not the case, you can definitely put the limit just on the collection tag itself.

**Comment by dannyuk1982** [comment]
Maybe it was a bug before that's been fixed since March, I haven't tried it since
