### ISSUE TITLE
Server Requirements incomplete

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-docs#205]
The Server Requirements in the docs to not list the PHP Fileinfo extension

    exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in /home/.../statamic/statamic/vendor/intervention/image/src/Intervention/Image/ImageManager.php:123

**Comment by jackmcdade** [comment]
Done.
