### ISSUE TITLE
Typo in routing redirects example?

### ISSUE THREAD

**Issue by jeffmckeand** [statamic/v2-docs#210]
In https://docs.statamic.com/routing#301-redirects, where demonstrating 301 redirects:

```yaml
redirects:
  /party: /my-long/page-name
```

Should `redirects` be singular (`redirect`)? Like...

```yaml
redirect:
  /party: /my-long/page-name
```

Found this when trying the technique on a site of mine. Plural was giving me 404s, but changing it to the singular magically made everything work.

I'm not sure which *should* be correct, just letting you know what actually works.

`¯\_(ツ)_/¯`

**Comment by jeffmckeand** [comment]
🎉

**Comment by jackmcdade** [comment]
I love it when I typo in the commit message, for all to see, for all time.
