### ISSUE TITLE
Broken link to URL Rewrites Info?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#216]
`https://docs.statamic.com/knowledge-base/homepage-only` has a link at the bottom of the page that points to `http://docs.statamic.com/getting-started#rewrites` but just 404s. 

(I would've suggested a fix, but have been having a hard time finding the right destination. So...  ?)

**Comment by jasonvarga** [comment]
I've just fixed the link. Thanks for pointing that out.
