### ISSUE TITLE
Please document: `{{ link to='somewhere' }}` ?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#218]
At least two inquiring minds would like to know more :-)

Chris Burton:
https://statamic.slack.com/archives/C04DJ02CR/p1495309828663877

Moi:
https://statamic.slack.com/archives/C252J9NJD/p1495479357600750

**Comment by iDGS** [comment]
Aaaaaand, since Jason points out Slack links are ephemeral, here's copy/pasted texts:

**chrisburton:**

Hmm. Perhaps it’s not documented. Idk.

It appears that `{{ link }}` gives you your URL while `to=""` is a variable set to append to the end (edited)

`link` = *http://test.com*
`to="something"` = *something*
`link to="something"` = http://test.com/something (edited)

hope that makes sense

---

**iDGS:**

Default install (Redwood theme) shows this interesting construct inside `nav.html`:
```{{ if logged_in }}
    <li><a href="{{ link to='users' }}">Users</a></li>
    <li><a href="{{ user:logout_url }}">Log out</a></li>
{{ else }}
    <li><a href="{{ link to='login' }}">Log in</a></li>
    <li><a href="{{ link to='register' }}">Register</a></li>
{{ /if }}
```

However, after running a fine-toothed comb through the online Docs, I can find no description of anything even close to `{{ link to='destination' }}`. Am I be barking up the wrong forest?

**Comment by jackmcdade** [comment]
We'll document it, it's okay, you don't need to do anymore research :)

**Comment by iDGS** [comment]
K.

But, but,... 

**Jason:** it just prepends the site url; from your locales
```
locales:
  en:
    url: http://mysite.com
```

`{{ link to="blog" }}`

http://mysite.com/blog

(Whew. Couldn't help myself. Compulsive documenter syndrome, LOL ;-)

**Comment by jackmcdade** [comment]
😶
