### ISSUE TITLE
`User:profile` docn usability upgrade?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#24]
RE: [https://docs.statamic.com/reference/tags/user-profile](https://docs.statamic.com/reference/tags/user-profile)

The following two sentences on this page could be repositioned to make things more clear:

> The `{{ user:profile }}` tag (or simply `{{ user }}`) will make all the fields in a user available.
> 
> If you don’t specify the user with either `id`, `username`, or `email` parameters, the currently logged in user will be shown.

At present they trail way behind the "Variables" heading. That's less than ideal placement.

The first of the two sentences could be moved up near the top of the page, to follow “Grab and display User data.”

The second sentence could follow the list of “Parameters”, and sit just _before_ the “Variables” heading.

I'll dig around to see if I can find where to make the actual edits and submit a pull request...

**Comment by iDGS** [comment]
(P.S. I really miss having links to make suggested improvements at the bottom of the doc pages.)

**Comment by jasonvarga** [comment]
The parameters have been edited to explain what happens when leaving them blank.
