### ISSUE TITLE
ToC for addons is missing pages

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-docs#241]
Missing `Site Helpers`, `Getting Started` & `Bootstrapping`

**Comment by edalzell** [comment]
I would submit a PR but I can't find the ToC in the repo

**Comment by jackmcdade** [comment]
The TOC is generated automatically based on headers with ids.

**Comment by edalzell** [comment]
There are headers w/ ids in this page, but this page is not in the ToC of addons

![docsindex md at master statamicdocs 2017-07-25 07-31-41](https://user-images.githubusercontent.com/6069653/28577340-5ac0a084-710b-11e7-8063-161a1b4e015a.png)
