### ISSUE TITLE
Control panel, Assets-container crops last item edit-menu

### ISSUE THREAD

**Issue by esonesson** [statamic/v2-docs#259]
Statamic 2.7.1

Browsing assets in the control panel, clicking the three dots on the last item. The part of the menu that overflows the container gets cropped. See attached screenshot.

When removing overflow: hidden on .asset-browser.card it's visible. 

<img width="667" alt="skarmavbild 2017-10-23 kl 10 43 24" src="https://user-images.githubusercontent.com/5310711/31879866-0a216648-b7df-11e7-9ae3-8fe99d38cfc5.png">

**Comment by jasonvarga** [comment]
Can you re-post this in statamic/v2-hub? This is the docs repo.
