### ISSUE TITLE
little typo in documentation on video fieldtype

### ISSUE THREAD

**Issue by pixelliquid** [statamic/v2-docs#280]
In the code example of the template `video` should be `video_url`:
```
{{ if video_url | is_embeddable }}
    <!-- Youtube and Video -->
    <iframe src="{{ video_url | embed_url }}" ...></iframe>
{{ else }}
    <!-- Other HTML5 video types -->
    <video src="{{ video_url | embed_url }}" ...></video>
{{ /if }}
```

**Comment by jackmcdade** [comment]
Only if the var name is `video_url`. We used `video` everywhere in this case. There is no naming requirement.

**Comment by pixelliquid** [comment]
I'm sorry mate. Apparently I made the typo myself (or better still, Atom with its code-completion and me not seeing this happening) so I'll be more careful opening an issue.
