### ISSUE TITLE
Bad link in Docs -> Fieldtypes -> Assets

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-docs#30]
Found a bad link in the docs: https://docs.statamic.com/reference/fieldtypes/assets

Clicking on `defaults` under the Settings section goes to https://docs.statamic.com/docs/fieldtypes#defaults instead of https://docs.statamic.com/reference/fieldtypes#default-settings

**Comment by 0xgdr** [comment]
Fixed, thank you.
