### ISSUE TITLE
Missing Fetch Fieldtype

### ISSUE THREAD

**Issue by itsHall** [statamic/v2-docs#304]
There is a Fetch fieldtype but it's not listed in the docs. There are others left out of the docs as well, though there may be a reasonable explanation.

![statamic docs fieldtypes](https://user-images.githubusercontent.com/31418688/38699998-af96749c-3e67-11e8-92d6-11dfcd5318dc.png)
![statamic interface fieldtypes](https://user-images.githubusercontent.com/31418688/38699999-afa5f26e-3e67-11e8-9fe1-068bf1a0ad5c.png)

**Comment by jasonvarga** [comment]
I believe the Fetch fieldtype you are seeing is [third party](https://statamic.com/marketplace/addons/fetch).

**Comment by itsHall** [comment]
You are correct, of course. Thanks, Jason!
