### ISSUE TITLE
Link to Laravel’s Blade syntax is going to a 404

### ISSUE THREAD

**Issue by FumbleGrumble** [statamic/v2-docs#314]
I was just reading through [https://docs.statamic.com/theming](https://docs.statamic.com/theming) and noticed that the link in this line "We also support Laravel’s Blade syntax by using the .blade.php file extension" goes to what appears to be a 404 page.

**Comment by jasonvarga** [comment]
Thanks!

In the future, if you're interested in contributing, there's an "Improve Content" button at the bottom of each page where you can edit it yourself.
