### ISSUE TITLE
View path appears to be broken on widgets

### ISSUE THREAD

**Issue by jesseschutt** [statamic/v2-docs#36]
Attempting to use `return $this->view('widget');` in an `AddonWidget.php` file returns the following error:

`FatalErrorException in DashboardController.php line 0:
Method Illuminate\View\View::__toString() must not throw an exception`

Dumping the `$directory` in `\Statamic\Extent\Extensible` on line 357 shows `"/home/vagrant/Sites/statamic2/statamic/bundles/Collection/resources/views"`. 

I'm assuming this should be referencing the addons path instead of the Collection path?

**Comment by jasonvarga** [comment]
Leaving this here for reference:

We chatted it out, looks like the view path bleeds over from the previous widget.
