### ISSUE TITLE
Forbidden characters for initial password

### ISSUE THREAD

**Issue by miezo** [statamic/v2-docs#405]
Just a minor issue: I created a user in site/users/someuser.yaml with an initial password that started with @
This broke the whole site. Of course you'd probably never do that...but maybe it should be catched without having to use debug mode.

**Comment by jasonvarga** [comment]
That's because `@` is a special character in YAML, you'll need to quote it.

Having a password starting with @ is fine, just gotta make sure it's quoted. If you created it in the control panel, I'm sure it would have done it.

```
password: '@mypassword'
```
