### ISSUE TITLE
Jack's favourite, an issue on teeny macbook screens with nav boxes

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-docs#45]
![the documentation - statamic 2 2016-04-29 07-40-18](https://cloud.githubusercontent.com/assets/6069653/14919503/02ddcdce-0dde-11e6-883b-33aba28e5754.png)
![the documentation - statamic 2 2016-04-29 07-40-49](https://cloud.githubusercontent.com/assets/6069653/14919504/02f87d2c-0dde-11e6-8d5c-e7a521dc90d5.png)

**Comment by jackmcdade** [comment]
Looks fine on my screen.

**Comment by than** [comment]
<img width="307" alt="screen shot 2016-04-29 at 9 48 13 am" src="https://cloud.githubusercontent.com/assets/510790/14919684/83f6b068-0def-11e6-9a2a-4c608662a5d7.png">

**Comment by edalzell** [comment]
you people and your large screens

**Comment by edalzell** [comment]
FYI, also occurs on my iPad
