### ISSUE TITLE
Add max_depth="2[or more]" to recursion nav tag example

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-docs#55]
I think we should update line 2 on the [Nav tag Recursion example](https://docs.statamic.com/reference/tags/nav#recursion) to something like:

`{{ nav from="/{segment_1}" max_depth="2"}}` 

Since the default max_depth seems to be 1, this code block didn't work out of the box for me :(

**Comment by jackmcdade** [comment]
Good call! I feel like this default should really be `2` anyway. Gonna make that change.
