### ISSUE TITLE
Funky 'active' class in DataFactories

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-docs#76]
![data factories - statamic 2 2016-08-06 16-12-59](https://cloud.githubusercontent.com/assets/6069653/17459543/36f133f6-5bf1-11e6-9565-bf515ff7f7d7.png)

Probably because I use Jack's favourite browser, Safari on a teeny tiny screen. DEAL WITH IT JACK.

**Comment by jackmcdade** [comment]
lol 😂
