### ISSUE TITLE
Conditions linking to wrong route

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-docs#88]
https://docs.statamic.com/reference/conditions gives an error. I believe it should be https://docs.statamic.com/conditions

/content/tags/collection.md
`There are a bunch of conditions available to you, like `:is`, `:isnt`, `:contains`, `:starts_with`, and `:is_before`. There are many more than that. In fact, there's a whole page dedicated to [conditions - check them out][conditions].`

**Comment by sheldonkotyk** [comment]
Look like there are issues with more than that.
https://docs.statamic.com/tags/asset is linking to 
 https://docs.statamic.com/reference/tags/assets
which errors. Looks like /reference is a problem.

**Comment by jackmcdade** [comment]
Yes, we just reorganized all the docs. I expected there to be some we missed. Don't worry about reporting them all, I'll be doing some find and replaces this weekend.
